In [1]:
# Import required packages
import torch
import pandas as pd
import numpy as np
import matplotlib, matplotlib.pyplot as plt

In [2]:
# Check versions to clarify if all required modules are installed and imported
print('PyTorch    :', torch.__version__)
print('Pandas     :', pd.__version__)
print('NumPy      :', np.__version__)
print('Matplotlib :', matplotlib.__version__)

PyTorch    : 2.7.1+cu118
Pandas     : 2.3.2
NumPy      : 2.3.3
Matplotlib : 3.10.6


------------------------------------------------------------------------------------------------------------------------
### Matrix Multiplication

#### Study material
* https://www.mathsisfun.com/algebra/matrix-multiplying.html



#### Types of matrix multiplication
* Element-wise multiplication
* Matrix multiplication

In [40]:
# Element-wise multiplication
X_TENSOR = torch.tensor([1, 2, 3])
X_TENSOR * X_TENSOR

tensor([1, 4, 9])

In [41]:
# Matrix multiplication
# 1*1 + 2*2 + 3*3 = 1 + 4 + 9 = 14
print(torch.matmul(X_TENSOR, X_TENSOR))

# also we can use @ for tensor multiplication
X_TENSOR @ X_TENSOR

tensor(14)


tensor(14)

In [42]:
%%time
# Check performance python vs PyTorch
1*1 + 2*2 + 3*3

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 4.29 μs


14

In [43]:
%%time
# Check performance python vs PyTorch
result = 0

for a in X_TENSOR:
    result += (a*a)

result

CPU times: user 1.17 ms, sys: 22 μs, total: 1.19 ms
Wall time: 792 μs


tensor(14)

In [44]:
%%time
torch.matmul(X_TENSOR, X_TENSOR)

CPU times: user 226 μs, sys: 33 μs, total: 259 μs
Wall time: 204 μs


tensor(14)

--------------------------------------------------------------------------------------------------------------------------------------

#### Rules of matrix multiplication

#### Study material
    * http://matrixmultiplication.xyz/

### 1. The inner dimensions must match.
   * Okay
     * `(2, 1) @ (1, 2)`
     * `(1, 2) @ (2, 1)`
   * Not Okay
     * `(2, 1) @ (2, 1)`
     * `(1, 2) @ (1, 2)`

In [45]:
# Case 1: Working
X_TENSOR = torch.rand(2, 1)
Y_TENSOR = torch.rand(1, 2)

# It will work
torch.matmul(X_TENSOR, Y_TENSOR)

tensor([[0.0635, 0.0275],
        [0.0585, 0.0254]])

In [46]:
# Case 2: Working
X_TENSOR = torch.rand(1, 2)
Y_TENSOR = torch.rand(2, 1)

# It will work
torch.matmul(X_TENSOR, Y_TENSOR)

tensor([[0.6302]])

In [47]:
# Case 2: Not Working
X_TENSOR = torch.rand(2, 1)
Y_TENSOR = torch.rand(2, 1)

# It will fail to run
try:
    torch.matmul(X_TENSOR, Y_TENSOR)
except RuntimeError as e:
    # Error but in red color
    print(f'\033[31m{e}\033[0m')

mat1 and mat2 shapes cannot be multiplied (2x1 and 2x1)


In [48]:
# Case 3: Not Working
X_TENSOR = torch.rand(1, 2)
Y_TENSOR = torch.rand(1, 2)

# It will fail to run
try:
    torch.matmul(X_TENSOR, Y_TENSOR)
except RuntimeError as e:
    # Error but in red color
    print(f'\033[31m{e}\033[0m')

mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)


### 1. The resulting matrix has the shape of the outer dimensions
   * `(2, 1) @ (1, 2)` -> `(2, 2)`
   * `(1, 2) @ (2, 1)` -> `(1, 1)`

In [49]:
# Case 1
X_TENSOR = torch.rand(2, 1)
Y_TENSOR = torch.rand(1, 2)

# Check the shape of Z_TENSOR
Z_TENSOR = torch.matmul(X_TENSOR, Y_TENSOR)
Z_TENSOR.shape

torch.Size([2, 2])

In [50]:
# Case 2
X_TENSOR = torch.rand(1, 2)
Y_TENSOR = torch.rand(2, 1)

# Check the shape of Z_TENSOR
Z_TENSOR = torch.matmul(X_TENSOR, Y_TENSOR)
Z_TENSOR.shape

torch.Size([1, 1])