In [2]:
# Import required packages
import torch
import pandas as pd
import numpy as np
import matplotlib, matplotlib.pyplot as plt

In [3]:
# Check versions to clarify if all required modules are installed and imported
print('PyTorch    :', torch.__version__)
print('Pandas     :', pd.__version__)
print('NumPy      :', np.__version__)
print('Matplotlib :', matplotlib.__version__)

PyTorch    : 2.7.1+cu118
Pandas     : 2.3.2
NumPy      : 2.3.3
Matplotlib : 3.10.6


------------------------------------------------------------------------------------------------------------------------------

### Manipulating Tensors / Tensor Operations

#### Addition

* `torch.add(tensor1, tensor2)` – Element-wise addition of two tensors.
* `tensor1 + tensor2` – Shorthand for element-wise addition.


#### Subtraction

* `torch.sub(tensor1, tensor2)` – Element-wise subtraction of tensor2 from tensor1.
* `tensor1 - tensor2` – Shorthand for element-wise subtraction.

#### Multiplication

* `torch.mul(tensor1, tensor2)` – Element-wise multiplication of two tensors.
* `tensor1 * tensor2` – Shorthand for element-wise multiplication.

#### Division

* `torch.div(tensor1, tensor2)` – Element-wise division of tensor1 by tensor2.
* `tensor1 / tensor2` – Shorthand for element-wise division.



In [6]:
# Simple addition
X_TENSOR = torch.tensor([1, 2, 3])
X_TENSOR + 10 # Simple addition

tensor([11, 12, 13])

In [10]:
# Simple subtraction
X_TENSOR = torch.tensor([10, 20, 30])
X_TENSOR - 10

tensor([ 0, 10, 20])

In [11]:
# Simple multiplication
X_TENSOR = torch.tensor([10, 20, 30])
X_TENSOR * 5

tensor([ 50, 100, 150])

In [12]:
# Simple division
X_TENSOR = torch.tensor([10, 20, 30])
X_TENSOR / 5

tensor([2., 4., 6.])

In [15]:
# Addition with pytorch in-built function
X_TENSOR = torch.tensor([1, 2, 3])
torch.add(X_TENSOR, 10)

tensor([11, 12, 13])

In [16]:
# Subtraction with pytorch in-built function
X_TENSOR = torch.tensor([50, 100, 150])
torch.sub(X_TENSOR, 50)

tensor([  0,  50, 100])

In [17]:
# Multiplication with pytorch in-built function
X_TENSOR = torch.tensor([15, 10, 5])
torch.mul(X_TENSOR, 3)

tensor([45, 30, 15])

In [18]:
# Division with pytorch in-built function
X_TENSOR = torch.tensor([15, 10, 5])
torch.div(X_TENSOR, 3)

tensor([5.0000, 3.3333, 1.6667])