In [1]:
# Import required packages
import torch
import pandas as pd
import numpy as np
import matplotlib, matplotlib.pyplot as plt

In [2]:
# Check versions to clarify if all required modules are installed and imported
print('PyTorch    :', torch.__version__)
print('Pandas     :', pd.__version__)
print('NumPy      :', np.__version__)
print('Matplotlib :', matplotlib.__version__)

PyTorch    : 2.7.1+cu118
Pandas     : 2.3.2
NumPy      : 2.3.3
Matplotlib : 3.10.6


------------------------------------------------------------------------------------------------------------------------
### Matrix Multiplication

#### Study material
* https://www.mathsisfun.com/algebra/matrix-multiplying.html



#### Types of matrix multiplication
* Element-wise multiplication
* Matrix multiplication

In [3]:
# Element-wise multiplication
X_TENSOR = torch.tensor([1, 2, 3])
X_TENSOR * X_TENSOR

tensor([1, 4, 9])

In [4]:
# Matrix multiplication
# 1*1 + 2*2 + 3*3 = 1 + 4 + 9 = 14
print(torch.matmul(X_TENSOR, X_TENSOR))

# also we can use @ for tensor multiplication
X_TENSOR @ X_TENSOR

tensor(14)


tensor(14)

In [5]:
%%time
# Check performance python vs PyTorch
1*1 + 2*2 + 3*3

CPU times: user 2 μs, sys: 1 μs, total: 3 μs
Wall time: 3.81 μs


14

In [6]:
%%time
# Check performance python vs PyTorch
result = 0

for a in X_TENSOR:
    result += (a*a)

result

CPU times: user 636 μs, sys: 103 μs, total: 739 μs
Wall time: 2.39 ms


tensor(14)

In [7]:
%%time
torch.matmul(X_TENSOR, X_TENSOR)

CPU times: user 179 μs, sys: 29 μs, total: 208 μs
Wall time: 128 μs


tensor(14)

--------------------------------------------------------------------------------------------------------------------------------------

#### Rules of matrix multiplication

#### Study material
    * http://matrixmultiplication.xyz/

### 1. The inner dimensions must match.
   * Okay
     * `(2, 1) @ (1, 2)`
     * `(1, 2) @ (2, 1)`
   * Not Okay
     * `(2, 1) @ (2, 1)`
     * `(1, 2) @ (1, 2)`

In [8]:
# Case 1: Working
X_TENSOR = torch.rand(2, 1)
Y_TENSOR = torch.rand(1, 2)

# It will work
torch.matmul(X_TENSOR, Y_TENSOR)

tensor([[0.1734, 0.2302],
        [0.2382, 0.3164]])

In [9]:
# Case 2: Working
X_TENSOR = torch.rand(1, 2)
Y_TENSOR = torch.rand(2, 1)

# It will work
torch.matmul(X_TENSOR, Y_TENSOR)

tensor([[0.6598]])

In [10]:
# Case 2: Not Working
X_TENSOR = torch.rand(2, 1)
Y_TENSOR = torch.rand(2, 1)

# It will fail to run
try:
    torch.matmul(X_TENSOR, Y_TENSOR)
except RuntimeError as e:
    # Error but in red color
    print(f'\033[31m{e}\033[0m')

mat1 and mat2 shapes cannot be multiplied (2x1 and 2x1)


In [11]:
# Case 3: Not Working
X_TENSOR = torch.rand(1, 2)
Y_TENSOR = torch.rand(1, 2)

# It will fail to run
try:
    torch.matmul(X_TENSOR, Y_TENSOR)
except RuntimeError as e:
    # Error but in red color
    print(f'\033[31m{e}\033[0m')

mat1 and mat2 shapes cannot be multiplied (1x2 and 1x2)


### 2. The resulting matrix has the shape of the outer dimensions
   * `(2, 1) @ (1, 2)` -> `(2, 2)`
   * `(1, 2) @ (2, 1)` -> `(1, 1)`

In [18]:
# Case 1
X_TENSOR = torch.rand(2, 1)
Y_TENSOR = torch.rand(1, 2)

Z_TENSOR = torch.matmul(X_TENSOR, Y_TENSOR)
# Check the shape of Z_TENSOR
Z_TENSOR.shape

torch.Size([2, 2])

In [19]:
# Case 2
X_TENSOR = torch.rand(1, 2)
Y_TENSOR = torch.rand(2, 1)

Z_TENSOR = torch.matmul(X_TENSOR, Y_TENSOR)
# Check the shape of Z_TENSOR
Z_TENSOR.shape

torch.Size([1, 1])

------------------
### Shape Error
- `(2, 1) @ (1, 2)` → **Shape Error**: The matrices are not aligned for multiplication because the inner dimensions do not match. Expected shape would be `(2, 2)`.
- `(1, 2) @ (2, 1)` → **Shape Error**: The matrices are not aligned for multiplication because the inner dimensions do not match. Expected shape would be `(1, 1)`.

### Normal Multiplication
- `(2, 3) @ (3, 2)` → **(2, 2)**: Matrix multiplication is valid, resulting in a matrix with shape `(2, 2)`.
- `(3, 2) @ (2, 4)` → **(3, 4)**: Matrix multiplication is valid, resulting in a matrix with shape `(3, 4)`.


In [24]:
# Shapes of matrix multiplication

X_TENSOR = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y_TENSOR = torch.tensor([
    [7, 8],
    [9, 10],
    [11, 12]
])


# It will fail to run
try:
    # mm is alias of matmul
    torch.mm(X_TENSOR, Y_TENSOR)
except RuntimeError as e:
    # Error but in red color
    print(f'\033[31m{e}\033[0m')

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


We can use **transpose** to fix our tensor shape issues by manipulating the shape of one of our tensors.

**transpose** -> Switches the axes or dimensions of a given tensor.

In [27]:
# Matrix without transoise
print(X_TENSOR)
# Matrix with transoise
print(X_TENSOR.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 3, 5],
        [2, 4, 6]])


In [28]:
# This will work because we use transpose
torch.mm(X_TENSOR.T, Y_TENSOR)

tensor([[ 89,  98],
        [116, 128]])

In [31]:
# Shape before and after transpose

# Before tranapose
print(X_TENSOR.shape, Y_TENSOR.shape)

# After tranapose
print(X_TENSOR.T.shape, Y_TENSOR.shape)

torch.Size([3, 2]) torch.Size([3, 2])
torch.Size([2, 3]) torch.Size([3, 2])
